export const REQUEST_LIKE_FRONT = 'NASA/REQUEST_LIKE_FRONT';
export const REQUEST_ADD_FRONT = 'NASA/REQUEST_ADD_FRONT';
export const REQUEST_EDIT_FORM = 'NASA/REQUEST_EDIT_FORM';
export const REQUEST_EDIT_FRONT = 'NASA/REQUEST_EDIT_FRONT';
export const REQUEST_CANCEL_EDIT = 'NASA/REQUEST_CANCEL_EDIT';
export const REQUEST_DELETE_FRONT = 'NASA/REQUEST_DELETE_FRONT';
export const REQUEST_FILTER_TYPE_FRONT = 'NASA/REQUEST_FILTER_TYPE_FRONT';
export const REQUEST_FILTER_DATE_FRONT = 'NASA/REQUEST_FILTER_DATE_FRONT';
export const REQUEST_FILTER_FAVOURITE_FRONT = 'NASA/REQUEST_FILTER_FAVOURITE_FRONT';
export const REQUEST_CANCEL_FILTER_FAVOURITE = 'NASA/REQUEST_CANCEL_FILTER_FAVOURITE';
export const REQUEST_SORT_TITLE_FRONT = 'NASA/REQUEST_SORT_TYPE_FRONT';
export const REQUEST_SORT_DATE_FRONT = 'NASA/REQUEST_SORT_DATE_FRONT';
export const REQUEST_CANCEL_SORT_DATE = 'NASA/REQUEST_CANCEL_SORT_DATE';
export const REQUEST_PAGINATION_FRONT = 'NASA/REQUEST_PAGINATION_FRONT';

export const REQUEST_SEARCH_NASA = 'NASA/REQUEST_SEARCH_NASA';
export const REQUEST_SEARCH_NASA_SUCCESS = 'NASA/REQUEST_SEARCH_NASA_SUCCESS';
export const REQUEST_SEARCH_NASA_FAIL = 'NASA/REQUEST_SEARCH_NASA_FAIL';